### sign up
POST http://localhost:8000/account/signup
Content-Type: application/json

{
    "username": "beerus2",
    "password": "123456",
    "first_name": "Beerus",
    "last_name": "Sama",
    "phone_number": "0123456785",
    "address": "97 Man Thiện",
    "day_of_birth": "1997-10-1",
    "gender": "0",
    "mail":"12354@gmail.com"
}

### login
POST http://localhost:8000/account/login
Content-Type: application/json

{
    "username": "sieuquaytihon80@gmail.com",
    "password": "123457"
}

### change info
PATCH http://localhost:8000/account/change_info
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjozLCJ1c2VybmFtZSI6ImJlZXJ1cyIsInJvbGUiOlt7ImlkX3JvbGUiOjEsImlzX2FjdGl2ZSI6dHJ1ZX0seyJpZF9yb2xlIjoyLCJpc19hY3RpdmUiOnRydWV9XSwiaWF0IjoxNjQ3NDIxNDE0fQ.9qq7TrqSw8zUGYga6ZuXyxWBw7NyFR4szdfgTq6GzVY
Content-Type: application/json

{
    "mail":"sieuquaytihon80@gmail.com"
}

### get information
GET http://localhost:8000/account/information?info=12345678
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjozLCJ1c2VybmFtZSI6ImJlZXJ1cyIsInJvbGUiOlt7ImlkX3JvbGUiOjEsImlzX2FjdGl2ZSI6dHJ1ZX0seyJpZF9yb2xlIjoyLCJpc19hY3RpdmUiOnRydWV9XSwiaWF0IjoxNjQ3NDIxNDE0fQ.9qq7TrqSw8zUGYga6ZuXyxWBw7NyFR4szdfgTq6GzVY

### forgot password
PATCH http://localhost:8000/account/forgot_password
Content-Type: application/json

{
    "username":"sieuquaytihon80@gmail.com",
    "code":"741405",
    "new_password":"123457"

}