### sign up
POST http://localhost:8000/account/signup
Content-Type: application/json

{
    "username": "beerus4",
    "password": "123456",
    "first_name": "Beerus",
    "last_name": "Sama",
    "phone_number": "0123456467",
    "address": "97",
    "day_of_birth": "1997-10-01",
    "gender": "0",
    "mail":"45678@gmail.com"
}

### login
POST http://localhost:8000/account/login
Content-Type: application/json

{
    "username": "beerus3",
    "password": "123456"
}

### change info
PATCH http://localhost:8000/account/change_info
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjoxLCJ1c2VybmFtZSI6ImJlZXJ1cyIsInJvbGUiOlt7ImlkX3JvbGUiOjIsImlzX2FjdGl2ZSI6bnVsbH1dLCJpYXQiOjE2NDkwMzkzMzl9.3Wa2j3bp-L7g0jvQJm8u53xA01VwfdsqMKvPMrWYgUs
Content-Type: application/json

{
    "mail":"sieuquaytihon80@gmail.com",
    "phone_number":"0321456789",
    "first_name":"beeeee",
    "last_name":"russsss"
}

### get information
GET http://localhost:8000/account/information?info=12345678b
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50Ijo2LCJ1c2VybmFtZSI6IkJlZXJ1czQiLCJyb2xlIjpbeyJpZF9yb2xlIjoyLCJpc19hY3RpdmUiOnRydWV9LHsiaWRfcm9sZSI6MywiaXNfYWN0aXZlIjp0cnVlfV0sImlhdCI6MTY1MzMxNDM4Mn0.-G3Z8Z0XXkacpJgxICmll9adP-SuThkCgvD09W7T_Ww

### forgot password
PATCH http://localhost:8000/account/forgot_password
Content-Type: application/json

{
    "username":"sieuquaytihon80@gmail.com",
    "code":"741405",
    "new_password":"123457"

}


### driver registration
POST http://localhost:8000/account/to_driver
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9hY2NvdW50IjozLCJ1c2VybmFtZSI6ImJlZXJ1czMiLCJyb2xlIjpbeyJpZF9yb2xlIjoyLCJpc19hY3RpdmUiOnRydWV9XSwiaWF0IjoxNjUzMjM2NzUzfQ.bbo5I6yLCAW3aOHcmOlMYBmYtiiivD0MLBNrtSHsXpw
Content-Type: application/json

{
    // driving_license, number_plate, id_transport_detail
    "driving_license" : "1234",
    "number_plate": "fwegweg",
    "id_transport_detail": 1
}